name: 'Publish evidence to Unify'
description: "Capture job-level evidence data and publish it to CloudBees Unify."

branding:
  icon: 'command'
  color: 'purple'

inputs:
  cloudbees-url:
    description: 'The CloudBees Unify URL.'
    required: false
    default: "https://api.cloudbees.io"
  content:
    description: 'The content to be published as evidence.'
    required: true
  format:
    description: 'The format of the evidence content.'
    required: false

runs:
  using: "docker"
  image: "docker://public.ecr.aws/l7o7z1g8/actions/gha-publish-evidence-item:main-9be3886ac98b5e268459e535d92fb4b8c161305c" 
  env:
    CLOUDBEES_API_URL: ${{ inputs.cloudbees-url }}
    CONTENT: ${{ inputs.content }}
