name: 'Publish evidence to Unify'
description: "Capture job-level evidence data and publish it to CloudBees Unify."

branding:
  icon: 'command'
  color: 'purple'

inputs:
  cloudbees-url:
    description: 'The CloudBees Unify URL.'
    required: false
    default: "https://api.cloudbees.io"
  content:
    description: 'The content to be published as evidence.'
    required: true
  format:
    description: 'The format of the evidence content.'
    required: false
  job-id:
    description: 'The ID of the job to associate the evidence with.'
    required: false
    default: ${{ job.check_run_id }}
    
runs:
  using: "docker"
  image: "docker://public.ecr.aws/l7o7z1g8/actions/gha-publish-evidence-item:main-bbbbeeefec91f3035e9d4f8bf9dfe3ee35281769b" 
  env:
    CLOUDBEES_API_URL: ${{ inputs.cloudbees-url }}
    CONTENT: ${{ inputs.content }}
    JOB_CHECK_RUN_ID: ${{ inputs.job-id }}
