name: 'Publish evidence to Platform'
description: "Capture job-level evidence data and publish it to the CloudBees platform."

branding:
  icon: 'command'
  color: 'purple'

inputs:
  cloudbees-url:
    description: 'The CloudBees platform URL.'
    required: false
    default: "https://api.cloudbees.io"
  content:
    description: 'The content to be published as evidence.'
    required: true
  format:
    description: 'The format of the evidence content.'
    required: false

runs:
  using: "docker"
  # image: "docker://public.ecr.aws/l7o7z1g8/actions/gha-publish-evidence-item:main-67ecddf177bea5bc3d61e1418bf3b6e4ea9e01e9" 
  image: "docker://ghcr.io/karthiknaveene/gha-action/gha-publish-evidence-action:latest"
  env:
    CLOUDBEES_API_URL: ${{ inputs.cloudbees-url }}
    CONTENT: ${{ inputs.content }}
